cp  paraConfigurations_2D.py paraConfigurations.py

#python makePlot_2D.py -t "DY_MC2016_e_eta1_eta2_ifMassZErr_2_3"
#python makePlot_2D.py -t "H_MC2016_e_eta1_eta2_ifMassHErr_2_2p5"
#python makePlot_2D.py -t "H_MC2016_e_eta3_eta4_ifMassHErr_2_2p5"
#python makePlot_2D.py -t "DY_2016_relpTErr_eta_ecalDriven_e"
#python makePlot_2D.py -t "mass4lErr_reco_refit_2e2mu"
#python makePlot_2D.py -t "mass4lErr_reco_refit_4mu"
#python makePlot_2D.py -t "mass4lErr_reco_refit_4e"
#python makePlot_2D.py -t "massZ1_diffM4lErr_4e"
#python makePlot_2D.py -t "massZ1_diffM4lErr_4mu"
#python makePlot_2D.py -t "massZ1_diffM4lErr_2e2mu"
#python makePlot_2D.py -t "diffPt_gen_reco_vs_genpT"
#python makePlot_2D.py -t "H4L_mu_eta_pt"
#python makePlot_2D.py -t "Z4L_mu_eta_pt"
#python makePlot_2D.py -t "ZZ4L_mu_eta_pt"
#python makePlot_2D.py -t "H4L_mu_residual_pt_eta_0_0p9"
#python makePlot_2D.py -t "H4L_mu_residual_pt_eta_0p9_1p4"
#python makePlot_2D.py -t "H4L_mu_residual_pt_eta_1p4_2p4"
#python makePlot_2D.py -t "Z4L_mu_residual_pt_eta_0_0p9"
#python makePlot_2D.py -t "Z4L_mu_residual_pt_eta_0p9_1p4"
#python makePlot_2D.py -t "Z4L_mu_residual_pt_eta_1p4_2p4"
#python makePlot_2D.py -t "ZZ4L_mu_residual_pt_eta_0_0p9"
#python makePlot_2D.py -t "ZZ4L_mu_residual_pt_eta_0p9_1p4"
#python makePlot_2D.py -t "ZZ4L_mu_residual_pt_eta_1p4_2p4"
#python makePlot_2D.py -t "ZZ4L_mu_ptResidual_m4l"
#python makePlot_2D.py -t "H4L_mu_residual_pt_eta_test1"
#python makePlot_2D.py -t "Z4L_mu_residual_pt_eta_test1"
#python makePlot_2D.py -t "ZZ4L_mu_residual_pt_eta_test1"

python makePlot_2D.py -t "mass4l_massZ2_2016Data"
python makePlot_2D.py -t "mass4l_massZ_closeMZ1MZ2_2016Data"
